-- Enables accurate Kitchen Metrics by tracking time spent in each stage

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS preparing_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS served_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS order_type TEXT DEFAULT 'dine_in',
ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE order_items
ADD COLUMN IF NOT EXISTS price_at_time NUMERIC;
